import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import eslintConfigPrettier from "eslint-config-prettier";

/** Next + TS rules; Prettier disables conflicting format rules. */
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  eslintConfigPrettier,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by scripts/copy-pdf-worker.mjs from the installed pdfjs-dist
    // and committed for deploy reliability (see that script's own comment) —
    // not hand-written, not meant to be linted.
    "public/pdf.worker.min.mjs",
  ]),
]);

export default eslintConfig;
