export type StoredFile = {
  fileKey: string;
  fileName: string;
  mimeType: string;
};

export type StoredFileBytes = {
  bytes: Buffer;
  fileName: string;
  mimeType: string;
};

/** A file already uploaded straight from the browser to Blob storage (see lib/direct-blob-upload.ts) — `adopt()` verifies it and folds it into this app's own StoredFile shape without re-uploading it. */
export type UploadedFileRef = {
  fileKey: string;
  fileName: string;
  mimeType: string;
};

export type FileStorage = {
  save(input: Readonly<{ file: File; folder: string }>): Promise<StoredFile>;
  /** Stores server-generated bytes (e.g. a filled Excel workbook) rather than an upload. */
  saveBuffer(
    input: Readonly<{
      bytes: Buffer;
      fileName: string;
      mimeType: string;
      folder: string;
    }>,
  ): Promise<StoredFile>;
  /**
   * Confirms a file the browser already uploaded directly to storage (bypassing
   * this app's own serverless functions — see lib/direct-blob-upload.ts for why)
   * and returns it in the same shape `save()` would have. Only meaningful for a
   * backend that supports direct client uploads (Blob); local disk storage has
   * no such path and rejects any call here.
   */
  adopt(input: UploadedFileRef): Promise<StoredFile>;
  read(fileKey: string): Promise<StoredFileBytes>;
};
