export type StoredFile = {
  fileKey: string;
  fileName: string;
  mimeType: string;
};

export type StoredFileBytes = {
  bytes: Buffer;
  fileName: string;
  mimeType: string;
};

export type FileStorage = {
  save(input: Readonly<{ file: File; folder: string }>): Promise<StoredFile>;
  /** Stores server-generated bytes (e.g. a filled Excel workbook) rather than an upload. */
  saveBuffer(
    input: Readonly<{
      bytes: Buffer;
      fileName: string;
      mimeType: string;
      folder: string;
    }>,
  ): Promise<StoredFile>;
  read(fileKey: string): Promise<StoredFileBytes>;
};
