import { describe, expect, it, vi } from "vitest";

const putMock = vi.fn();
const headMock = vi.fn();

vi.mock("@vercel/blob", () => ({
  put: (...args: unknown[]) => putMock(...args),
  head: (...args: unknown[]) => headMock(...args),
}));

// Imported after the mock so the module under test picks up the mocked SDK.
const { vercelBlobStorage } = await import(
  "@/modules/files/infrastructure/vercel-blob-storage"
);

describe("vercelBlobStorage", () => {
  it("stores an uploaded File privately under the ditanik/ prefix and strips it back off the returned fileKey", async () => {
    putMock.mockResolvedValueOnce({ pathname: "ditanik/lpo-originals/abc-order.pdf" });
    const file = new File([new Uint8Array([1, 2, 3])], "order.pdf", {
      type: "application/pdf",
    });

    const result = await vercelBlobStorage.save({ file, folder: "lpo-originals" });

    expect(putMock).toHaveBeenCalledTimes(1);
    const [pathArg, , optionsArg] = putMock.mock.calls[0] as [string, unknown, Record<string, unknown>];
    expect(pathArg.startsWith("ditanik/lpo-originals/")).toBe(true);
    expect(pathArg.endsWith("-order.pdf")).toBe(true);
    expect(optionsArg.access).toBe("private");

    expect(result.fileKey).toBe("lpo-originals/abc-order.pdf");
    expect(result.fileName).toBe("order.pdf");
  });

  it("stores server-generated bytes under the requested folder/name and mime type", async () => {
    putMock.mockResolvedValueOnce({ pathname: "ditanik/generated-documents/xyz-AHO-INV.xlsx" });

    const result = await vercelBlobStorage.saveBuffer({
      bytes: Buffer.from("fake xlsx bytes"),
      fileName: "AHO-INV-23072026-01.xlsx",
      mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      folder: "generated-documents",
    });

    expect(result.fileKey).toBe("generated-documents/xyz-AHO-INV.xlsx");
    expect(result.fileName).toBe("AHO-INV-23072026-01.xlsx");
    expect(result.mimeType).toBe(
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    );
  });

  it("rejects a fileKey containing '..' before ever calling out to Blob", async () => {
    await expect(vercelBlobStorage.read("../../etc/passwd")).rejects.toThrow(/invalid file key/i);
    expect(headMock).not.toHaveBeenCalled();
  });
});
